### ISSUE TITLE
Support Windows install

### ISSUE THREAD

**Issue by shprink** [wordpress-clients/hybrid#39]

**Comment by gonzaloplaza** [comment]
Found issue installing npm libraries on Windows (>v1.4.0). I'm not sure if this is an error related to windows or maybe dependencies/configs

![ionic-wp-error](https://cloud.githubusercontent.com/assets/1164633/9304110/facd7d7c-44e4-11e5-9e75-6e41aea67292.jpg)

**Comment by shprink** [comment]
Make sure you use the latest version 1.4.2.

If you still have issue installing, I am sorry but Windows support is not planned yet. If you are interested to debug and share your discoveries with us I'd be happy to merge whatever can help Windows users.

Cheers

**Comment by gonzaloplaza** [comment]
Hey Julien, i found this article related to windows and node-gyp:

https://www.robertkehoe.com/2015/03/fix-node-gyp-rebuild-error-on-windows/

For Windows 7 users, Visual Studio, Windows SDK 7.1, Visual C++ compiler and Python 2.7.3 are required.

After the installation of these components, "npm install" command worked fine.

Regards

**Comment by shprink** [comment]
@SilentKernel had the app running on Windows lately. Can you explain how you did that please ?

**Comment by shprink** [comment]
@mbaljeetsingh is also interested

**Comment by SilentKernel** [comment]
On Windows you must install Python before trying to run WPHC.
On my computer there is also Microsoft Visual Studio installed (installer of Visual Studion installed Cordova (advanced install).

Then the biggest problem is that WPHC uses Unix command (rm for example) and .sh file, you juste have to edit package.json to switch Unix command (like rm) with Windows alternative (del). also install.sh can be easly understood and can be rewritten with batch (copy instead of cp for example :))

But on Windows there is also the possibility to use Unix Command Line, Git installer on windows allow you to add Unix Like binary on your PATH environement then you will be able to use rm or even cp

Then release.sh can't work ATM on windows, but you can easly make your own (if your android SDK and NDK is in your path it will easer !)

**Comment by jinsley8** [comment]
Has anyone tried partitioning part of a Windows drive to run Mac OS X?

**Comment by shprink** [comment]
@jinsley8 you can have a dual boot with Ubuntu easily from Windows. https://help.ubuntu.com/community/WindowsDualBoot

**Comment by gonzaloplaza** [comment]
Guys you also can install VirtualBox and Ubuntu Virtual Machine instead.

**Comment by mbaljeetsingh** [comment]
@SilentKernel After installation i am getting this error,
**Error: ENOENT, open 'C:\xampp\htdocs\wordpress-hybrid-client\www\index.html'**

I have android sdk and ndk in the path (correctly). But how can i rewrite release.sh file for windows.

**Comment by Prabhat36** [comment]
hi, the best solution for this is
to create partition on your hard drive and install linux os,
and the proceed for further.. this is the only way..

**Comment by iffifan** [comment]
Use vagrant

**Comment by dmastag** [comment]
Hi @iffifan 
Any good vagrant boxes recommendations to use?
I already tried using vagrant with no success.

**Comment by shprink** [comment]
If you guys use docker I made an image https://github.com/shprink/wphc-dockerbox

**Comment by eTiTan** [comment]
One fast solution, in windows have problems chacing images, if you comment this line, it works, but it's not a defenitive solution.

\lib\init\init.service.coffee line 5

![imgcache](https://cloud.githubusercontent.com/assets/1615920/12946077/0e2d00f2-cff2-11e5-8250-641b133b878a.jpg)

**Comment by Devpheara** [comment]
I can not use yarn command on mac it tell yarn command not found

**Comment by shprink** [comment]
https://yarnpkg.com/en/docs/install#mac-tab

**Comment by PabloWestphalen** [comment]
Heads up: Successfully managed to install and run under Windows 10 (with the Creators update*) Ubuntu bash following the default linux instructions.

The only real issue faced was that running `apt-get install nodejs` got me some ancient version like 0.10 or whatever. Had to remove it, add this custom repository: https://deb.nodesource.com/setup_6.x as explained in this tutorial (https://aigeec.com/installing-node-js-on-windows-10-bash/) and then reinstall in order to get it all going.

Altough a funny mishap that happened was when i first ran 'yarn', i got a system message that that application was not installed, and a suggestion to add it via 'apt-get install yarn'. Which i ran, but got me a different tool. If by any chance you get the "There are no scenarios; must have at least one." error when running yarn, it means you have the wrong one. Remove this wrong, system-level yarn with apt-get then get the correct one via npm.

* The latest creators update is required because previous builds of windows 10 lack a network interface implementation that is required to launch the LiveReload server [amongst other things most likely].

**Comment by suyoto1986** [comment]
Hello, I'm interested with this project but i had error, could you please inform me how to solve?

when i run npm start, terminal going like this:
root@ubuntu:/home/suyoto# npm start
npm ERR! Linux 3.13.0-123-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! path /home/suyoto/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/home/suyoto/package.json'
npm ERR! enoent ENOENT: no such file or directory, open '/home/suyoto/package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /home/suyoto/npm-debug.log

**Comment by suyoto1986** [comment]
sorry, wrong issue.
aand lready commented on this
https://github.com/wordpress-clients/hybrid/issues/359

**Comment by shprink** [comment]
Should be fine with v3 (currently `develop` branch)
